<a href="https://colab.research.google.com/github/juwon-ds/practice-data-analysis/blob/main/day2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    'name': ['Juwon', 'Minji', 'Alex', 'Sara', 'Tom'],
    'score': [85, 92, 78, 88, 95],
    'age': [20, 21, 19, 22, 20]
}

df = pd.DataFrame(data)
print(df)

    name  score  age
0  Juwon     85   20
1  Minji     92   21
2   Alex     78   19
3   Sara     88   22
4    Tom     95   20

In [2]:
#정렬
df.sort_values('score',ascending=False)

    name  score  age
4    Tom     95   20
1  Minji     92   21
3   Sara     88   22
0  Juwon     85   20
2   Alex     78   19

In [3]:
df.sort_values('name')

    name  score  age
2   Alex     78   19
0  Juwon     85   20
1  Minji     92   21
3   Sara     88   22
4    Tom     95   20

In [4]:
#여러 조건 필터
df[(df['score']>=80) & (df['age']>=20)]

    name  score  age
0  Juwon     85   20
1  Minji     92   21
3   Sara     88   22
4    Tom     95   20

In [5]:
df[(df['score']>=90) & (df['age']<20)]

Empty DataFrame
Columns: [name, score, age]
Index: []

& AND

| OR

괄호 필수!!

In [8]:
#column 추가
df['pass'] = df['score']>=80
print(df)

    name  score  age   pass
0  Juwon     85   20   True
1  Minji     92   21   True
2   Alex     78   19  False
3   Sara     88   22   True
4    Tom     95   20   True

In [9]:
#간단 분석
df['age'].mean()

np.float64(20.4)

In [10]:
df['score'].max()

95

Quiz

In [12]:
#score 기준 내림차순 정렬
print(df.sort_values('score', ascending = False))

    name  score  age   pass
4    Tom     95   20   True
1  Minji     92   21   True
3   Sara     88   22   True
0  Juwon     85   20   True
2   Alex     78   19  False

In [14]:
#age가 20 이상인 사람만 출력
print(df[df['age']>=20])

    name  score  age  pass
0  Juwon     85   20  True
1  Minji     92   21  True
3   Sara     88   22  True
4    Tom     95   20  True

In [16]:
#score ≥ 80 AND age ≥ 20인 사람 출력
df[(df['score']>=80) & (df['age']>=20)]

    name  score  age  pass
0  Juwon     85   20  True
1  Minji     92   21  True
3   Sara     88   22  True
4    Tom     95   20  True

In [17]:
#score ≥ 90인 사람의 이름만 출력
df[(df['score']>=90)]['name']

1    Minji
4      Tom
Name: name, dtype: object

In [19]:
#pass 컬럼 추가 (80 이상 = True)
df['pass'] = df['score']>=80
print(df)

    name  score  age   pass
0  Juwon     85   20   True
1  Minji     92   21   True
2   Alex     78   19  False
3   Sara     88   22   True
4    Tom     95   20   True

In [21]:
#pass가 True인 사람들의 평균 score
df[df['pass']==True]['score'].mean()

np.float64(90.0)