<a href="https://colab.research.google.com/github/juwon-ds/practice-data-analysis/blob/main/notebooks/day3_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    'name': ['Juwon', 'Minji', 'Alex', 'Sara', 'Tom', 'John'],
    'score': [85, 92, 78, 88, 95, 70],
    'age': [20, 21, 19, 22, 20, 21],
    'gender': ['F', 'F', 'M', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
print(df)

    name  score  age gender
0  Juwon     85   20      F
1  Minji     92   21      F
2   Alex     78   19      M
3   Sara     88   22      F
4    Tom     95   20      M
5   John     70   21      M

df.groupby('기준')['값'].함수()

--> 기준 여러 개인 경우 (['기준'])

--> 값 여러 개인 경우 [['값']]

In [2]:
df.groupby('gender')['score'].mean()

gender
F    88.333333
M    81.000000
Name: score, dtype: float64

In [3]:
df.groupby('gender')['score'].max()

gender
F    92
M    95
Name: score, dtype: int64

In [4]:
df.groupby('gender')['name'].count()

gender
F    3
M    3
Name: name, dtype: int64

Quiz

In [15]:
#성별 평균 나이 구하기
df.groupby('gender')['age'].mean()

gender
F    21.0
M    20.0
Name: age, dtype: float64

In [16]:
#성별 최고 점수 구하기
df.groupby('gender')['score'].max()

gender
F    92
M    95
Name: score, dtype: int64

In [17]:
#성별 인원 수 구하기
df.groupby('gender')['name'].count()

gender
F    3
M    3
Name: name, dtype: int64

In [19]:
#성별 평균 점수가 더 높은 성별 찾기
df.groupby('gender')['score'].mean().idxmax()

#max() = 값
#idxmax() = 위치(이름)

'F'

In [22]:
#성별 평균 점수 + 평균 나이 동시에 보기
df.groupby('gender')[['score','age']].mean()

#여러 컬럼은 이중 대괄호 [[]] !!

            score   age
gender
F       88.333333  21.0
M       81.000000  20.0