<a href="https://colab.research.google.com/github/juwon-ds/practice-data-analysis/blob/main/notebooks/day4_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# CSV 데이터 사용

import pandas as pd

data = {
    'name': ['Juwon', 'Minji', 'Alex', 'Sara', 'Tom'],
    'score': [85, None, 78, 88, None],
    'age': [20, 21, None, 22, 20]
}

df = pd.DataFrame(data)
print(df)

    name  score   age
0  Juwon   85.0  20.0
1  Minji    NaN  21.0
2   Alex   78.0   NaN
3   Sara   88.0  22.0
4    Tom    NaN  20.0

In [3]:
# 결측치 확인

df.isnull()

    name  score    age
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [4]:
df.isnull().sum()

name     0
score    2
age      1
dtype: int64

In [5]:
# 결측치 제거

df.dropna()

    name  score   age
0  Juwon   85.0  20.0
3   Sara   88.0  22.0

In [6]:
df.dropna(subset=['score'])

    name  score   age
0  Juwon   85.0  20.0
2   Alex   78.0   NaN
3   Sara   88.0  22.0

In [7]:
# 결측치 채우기

df['score'].fillna(df['score'].mean())

0    85.000000
1    83.666667
2    78.000000
3    88.000000
4    83.666667
Name: score, dtype: float64

In [9]:
df['score'] = df['score'].fillna(df['score'].mean())

In [10]:
print(df)

    name      score   age
0  Juwon  85.000000  20.0
1  Minji  83.666667  21.0
2   Alex  78.000000   NaN
3   Sara  88.000000  22.0
4    Tom  83.666667  20.0

In [11]:
# 실전에서의 사용 예

df.head()
df.isnull().sum()
df['score'] = df['score'].fillna(df['score'].mean())
df.groupby('name')['score'].mean()

name
Alex     78.000000
Juwon    85.000000
Minji    83.666667
Sara     88.000000
Tom      83.666667
Name: score, dtype: float64

Quiz

In [13]:
# 각 컬럼의 결측치 개수 구하기

df.isnull().sum()

name     0
score    0
age      1
dtype: int64

In [15]:
# score 결측치 있는 행 삭제

df.dropna(subset='age')

    name      score   age
0  Juwon  85.000000  20.0
1  Minji  83.666667  21.0
3   Sara  88.000000  22.0
4    Tom  83.666667  20.0

In [16]:
# score 결측치를 평균으로 채우기

df.fillna(df['score'].mean())

    name      score        age
0  Juwon  85.000000  20.000000
1  Minji  83.666667  21.000000
2   Alex  78.000000  83.666667
3   Sara  88.000000  22.000000
4    Tom  83.666667  20.000000

In [18]:
# age 결측치를 평균으로 채우고 성별 평균 나이 구하기

df['gender'] = ['F', 'F', 'M', 'F', 'M']
df.fillna(df['age'].mean())
df.groupby('gender')['age'].mean()

gender
F    21.0
M    20.0
Name: age, dtype: float64

In [20]:
# score 결측치 처리 후 성별 평균 점수 구하기

df.dropna(subset = 'score')
df.groupby('gender')['score'].mean()

gender
F    85.555556
M    80.833333
Name: score, dtype: float64