<a href="https://colab.research.google.com/github/juwon-ds/practice-data-analysis/blob/main/notebooks/day8_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    'name': ['Juwon', 'Minji', 'Alex', 'Sara', 'Tom', 'John'],
    'age': [20, 21, 19, 22, 20, 23],
    'score': [85, 90, 65, 88, 95, 70],
    'gender': ['F', 'F', 'M', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
df

    name  age  score gender
0  Juwon   20     85      F
1  Minji   21     90      F
2   Alex   19     65      M
3   Sara   22     88      F
4    Tom   20     95      M
5   John   23     70      M

In [7]:
# 조건 필터링

# 점수가 80 이상이고, 성별이 F인 사람
df[(df['score']>=80) & (df['gender']=='F')]

    name  age  score gender
0  Juwon   20     85      F
1  Minji   21     90      F
3   Sara   22     88      F

In [8]:
# 정렬

# 점수 높은 순으로 정렬
df.sort_values('score', ascending=False)

    name  age  score gender
4    Tom   20     95      M
1  Minji   21     90      F
3   Sara   22     88      F
0  Juwon   20     85      F
5   John   23     70      M
2   Alex   19     65      M

In [10]:
df.query('age >= 20 and score >= 80')

    name  age  score gender
0  Juwon   20     85      F
1  Minji   21     90      F
3   Sara   22     88      F
4    Tom   20     95      M

In [11]:
df.query('score >= 85 and gender == "M"')

  name  age  score gender
4  Tom   20     95      M

In [14]:
# groupby

# 성별별로 평균 점수, 최대 점수 한 번에 구하기

df.groupby('gender')['score'].agg(['mean', 'max'])

             mean  max
gender
F       87.666667   90
M       76.666667   95

In [15]:
df.query('score >= 80').groupby('gender')['score'].mean()

gender
F    87.666667
M    95.000000
Name: score, dtype: float64